- name: variables
  hosts: localhost
  vars:
    URL: sample.com
  tasks:
    - name: print url variable
      ansible.builtin.debug:
        msg: "{{ URL }}"

- name: Task variable
  hosts: localhost
  tasks:
    - name: print URL1 variables
      ansible.builtin.debug:
        msg: "{{ URL1 }}"
      vars:
        URL1: sample.com
    - name: print URL2 variables
      ansible.builtin.debug:
        msg: "{{ URL2 }}"
      vars:
        URL2: example.com

- name: Register variable
  hosts: localhost
  tasks:
    - name: get uptime of server
      ansible.builtin.shell: uptime
      register: OUT
    - name: print out var
      ansible.builtin.debug:
        msg: "{{ OUT }}"